import { ThemeProvider } from '@/components/theme/ThemeProvider';
import ProgressTopBar from '@/components/ProgressTopBar';
import { Toaster } from '@/components/ui/toaster';
import Container from '@/components/Container';
import { Inter } from 'next/font/google';
import '../globals.css';
import { EdgeStoreProvider } from '@/lib/edgestore';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Alert from '@/components/Alert';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EdgeStoreProvider>
          <ThemeProvider attribute="class" defaultTheme="light">
            <ProgressTopBar />
            <Container>{children}</Container>
            <Toaster />
          </ThemeProvider>
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
