import Products from '@/components/pages/Products';
import { Button } from '@/components/ui/button';
import React from 'react';

export const metadata = {
  title: 'EzRent | Products',
  description: 'Generated by create next app',
};

export default function page() {
  return (
    <>
      <Products />
    </>
  );
}
